id: 6f2c27235cb740f7bc8be6e4131547c6
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_498-Tantra_of_the_Blue-Clad_Vajrapani-v1
  language: bo
  author: ''
  volume: {}
